/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import MoneyBox from "./MoneyBox";
import type { PlaneProps, Triplet } from "@react-three/cannon";
import { useAnimations, useGLTF, useTexture } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { useEffect, useMemo, useRef, useState } from "react";
import { useBox, useTrimesh } from "@react-three/cannon";
import type { InstancedMesh, Mesh, Color } from "three";

const Boxes = () => {
  const [isOpen, setIsOpen] = useState(true);
  const args: Triplet = [0.05, 0.1, 0.2];
  const number = 80;

  const [ref, { at }] = useBox(
    () => ({
      args,
      mass: 1,
      position: [2 - Math.random(), 5 - Math.random(), Math.random() - 0.5 + 100],
    }),
    useRef<InstancedMesh>(null)
  );
  useFrame(() => {
    if(!ref.current) return;
    if(!isOpen) return;
    at(Math.floor(Math.random() * number)).position.set(
      2 - Math.random(),
      5.2 - Math.random(),
      Math.random()
    )
  }
  );
  return (
    <> 
    <MoneyBox isOpen={isOpen} setIsOpen={setIsOpen} />
    
    <instancedMesh ref={ref} args={[undefined, undefined, number]}>
      <boxGeometry args={args}>
      </boxGeometry>
      <meshToonMaterial color="#00b500" />
    </instancedMesh>
    </>
  );
};

export default Boxes;
