/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";

export default function Model(): JSX.Element {
  const { nodes } = useGLTF("./congresso-v2.glb");

  const bakedTexture = useTexture("./congresso-baked.jpg");
  bakedTexture.flipY = false;
  bakedTexture.encoding = THREE.sRGBEncoding;

  const bakedMaterial = new THREE.MeshBasicMaterial({
    map: bakedTexture,
  });

  return (
    <group>
      <mesh
        material={bakedMaterial}
        geometry={nodes.Plane004.geometry}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("./CONGRESSO.glb");
